#!/bin/bash
cd /sys/kernel/config/usb_gadget/
mkdir -p cryptanefido
cd cryptanefido
echo 0x1d6b > idVendor 
echo 0x0104 > idProduct 
echo 0x0100 > bcdDevice 
echo 0x0200 > bcdUSB 
mkdir -p strings/0x409
echo "fedcba9876543210" > strings/0x409/serialnumber
echo "Cryptane" > strings/0x409/manufacturer
echo "FIDO Key" > strings/0x409/product
mkdir -p configs/c.1/strings/0x409
echo "Config 1: ECM network" > configs/c.1/strings/0x409/configuration
echo 250 > configs/c.1/MaxPower

mkdir -p functions/hid.usb0
echo 1 > functions/hid.usb0/protocol
echo 1 > functions/hid.usb0/subclass
echo 8 > functions/hid.usb0/report_length
echo -ne \\x06\\xd0\\xf1\\x09\\x01\\xa1\\x01\\x09\\x20\\x15\\x00\\x26\\xff\\x00\\x75\\x08\\x95\\x40\\x81\\x02\\x09\\x21\\x15\\x00\\x26\\xff\\x00\\x75\\x08\\x95\\x40\\x91\\x02\\xc0 > functions/hid.usb0/report_desc
ln -s functions/hid.usb0 configs/c.1/
ls /sys/class/udc > UDC
